[files]
# Temporarily commenting a lot so that at least *.sol files are included.
extend-exclude = [
    "CHANGELOG.md",
    "**/automata-attestation/**",
    "**/thirdparty/**",
    "**/compiled/**",
]
