name: "CI"

on:
  push:
    branches: [main]
    paths:
      - "packages/taiko-client/**"
  pull_request:
    paths:
      - "packages/taiko-client/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache: true

      - name: Lint
        working-directory: packages/taiko-client
        run: make lint

  integration_tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.4.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install protocol dependencies
        working-directory: packages/protocol
        run: pnpm install

      - name: Test
        working-directory: packages/taiko-client
        run: |
          TAIKO_MONO_DIR=${GITHUB_WORKSPACE} make test

      - name: Codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: ${{ env.CLIENT_DIR }}/coverage.out
